# -*- coding: utf-8 -*-
"""python_13_inter-mid_01_분기문과 반복문.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bzUwGrGLdcN-AjXDf9wWRwueOiPl7bJQ

분기문과 반복문
"""

# for 반복문
# i, sum = 0, 0  #  초기값 설정

sum = 0

for i in range(1,11,1):
    #range(start, end, interval)
    sum = sum + i
    # i 만큼 증가함

    # 변화과정 확인
    #print(i)
    #print(sum)  # 누적합

# 결과물 출력
print("1에서 10까지 합은? : %d"%sum)

for i in range(1,11,1):
    print(i)

for i in range(1,11,2):
    print(i)

# 구구단(중첩 for 반복문)

i, k = 0, 0 # 초기화

for i in range(2, 10, 1):
    for k in range(1, 10, 1):
        print("%d * %d = %2d"%(i, k, i*k))

    print("-" * 10)

# f" {} " : f-string 문자열 포맷 함수(python3 이후 최신)
# format 함수
# %d :decimal : 숫자(정) %s : string (python2)

# %d : 문자열에서 정수 값 삽입

age = 20
txt = "나는 %d살입니다."%age

print(txt)

# %s : s(str) 문자열에서 문자 값을 삽입

name = "Dr.Will"
txt = "My name is %s"%name
print(txt)

# %2d : 정수값의 너비 지정

number = 7
formatted_num = "%4d" % number
print(formatted_num)
# 출력이 앞에 공백 추가 2문자 너비 구성됨
# 7로 출력되고 앞의 공백 1개 있음

number = 27
formatted_num = "%2d" % number
print(formatted_num)

for i in range(1,101):
    print("for 반복문을 %d번 실행합니다"%i)

# break 문 (정지조건)

for i in range(1,101):
    print("for 반복문을 %d번 실행합니다"%i)
    break

# continue문 (~제외)

i, sum = 0, 0 # 초기화

for i in range(1,101):
    if i % 3 == 0:  #3의 배수이면
        continue # 제외 >> 건너 뛰어

    sum += i # sum = sum + i

    # 실행과정 확인
    # print(i)
    # print(sum)

# 최종 결과 (3의 배수 제외한 1~10까지 합계)
print("3의 배수 제외한 1~10까지 합계: %d"%sum)

