# -*- coding: utf-8 -*-
"""python_08_list_comprehension_lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WK53UcAaRiTxMDCLi9Pu8tzQvOOb-zoY

list_comprehension(리스트 컴프리헨션)
"""

# 반복문을 사용, 0~10까지 숫자를 리스트로 만들어요

# for 문 사용
number=[]

for i in range(10+1):
    number.append(i)

print(number)

number=[]

for i in range(10+1):
    number.append(i)

print(number)

number=[]

for i in range(10+1):
    number.append(i)

    print(number)

# list comprehension

number = [x for x in range(10+1)]

print(number)

"""조건문이 있는 리스트 컴프리헨션"""

# 0~10까지 숫자 중에서 홀수만 모아서 새 리스트로 만들어라
# for / range / %2 == 1

# for문으로 만들어보기

odds =[]

for i in range(10+1):
    if i%2 == 1:
        odds.append(i)


print(odds)

# list comprehension 만들기

odds = [x for x in range(10+1) if x%2 ==1]
print(odds)

"""조건이 2개라면?"""

# 0 ~ 10까지 숫자 중, 홀수이고 5 보다 작은 수

# 리스트 컴플리헨션으로 만들어 주세요

odds = [x for x in range(10+1) if x%2 == 1 if x<5]
print(odds)

"""이중 반복문(for문이 2개) 를 list comprehension으로 바꾼다면?"""

가게 = ['올리브영','세븐일레븐','엘지25']
제품 = ['폰 충전기','물티슈','콜라']

살거 = [(x,y) for x in 가게 for y in 제품]

print(살거)

"""lambda (람다) 식"""

# 람다식 : 매개변수와 매개변수가 들어갈 식(함수)를 한 줄로 표현(일회용 함수)

x = 4
y = 7

x + y

"""람다식을 왜 쓰지?
- x+y 값이 계속 바뀐다고 생각해봐...매번 변수를 다르게 정의해 줘야 해용 >> 아우 ! 귀찮아
"""

lambda x, y : x+y

(lambda x,y : x+y)(8,10)

(lambda x, y: 2**x + 3)(2,3)

lambda x, y : x+y

