# -*- coding: utf-8 -*-
"""python_15_inter-mid_문자열.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilFZ50DxpUwirkveF7oeddNZqDnHGm1X

문자열 기본
"""

a = [1,2,3,4,5]

print(a[0])
print(a[1:3])

s = "멀티캠퍼스_데이터분석 및 개발자과정_8기"
s[6:]

# count() : 찾을 문자열이 몇 개 있는 지, 개수를 세는 함수

s.count("_")

# find() : 찾을 문자열이 왼쪽 끝(0번 위치) 시작해서 몇 번째 위치에 있는 지 확인
# 만약, 찾을 문자열이 없으면 '-1' 출력됨

s.find('멀티')

s.find('선릉')
# 찾는 문자열이 없음 >> '-1' 반환

# index() : find() 유사함. 단, 없으면 에러 발생

'''
s.index('선릉')
ValueError: substring not found
'''

# join()

a =','
a.join(['name','addr','email'])

a ='/'
a.join(['name','addr','email'])

"""문자열 중요 내장 함수"""

# upper / lower

# upper : 전부 대문자로 변환
a = 'MultiCampus'
a.upper()

# lower : 전부 소문자로 변환
b = "BIG_DATA"
b.lower()

print(a)

a.replace('C','c')

a

a = a.replace('C','c')
print(a)

d = 'dat1 dat2 dat3'
e = d.replace(' ','') # 공백도 문자로 인식 >> "" 없애라는 의미

print(d)
print(e)

ai = "나는 인공지능 데이터분석가 및 개발자다"

print(ai)
print(ai.split(' '))
# 공백 기준, 분리

f = "          닥터윌    "

print(f.lstrip()) # 왼쪽을 벗겨내
print(f.rstrip()) # 오른쪽을 벗겨내
print(f.strip())  # 양쪽 다 벗겨내

a

a.swapcase()

h = 'dr.will'

print(h)

print(h.title())

# startwith, endswith

s = '닥터윌과 함께 하는 파이썬 공부는 너무 잼나요? 말해봐요, 어여~'
print(s)

s.startswith('닥터윌')

s.startswith('파이썬')

s.endswith('어여~')

s.endswith('^^')

"""문자열 분리 및 결합
- split(), join(), splitlines()
"""

ss = '닥터윌과 함께 파이썬을 열공하는 중... 한숨이 나옴'
ss.split()

aa = '5시:40분: 끝내줄까?'
aa.split(':')

bb = '제발요\n안그러면\n수업거부'
print(bb)

bb.split('\n')

bb.splitlines()

cc = '/'
cc.join('닥터윌')

# 문자열
# 연/월/일 형식으로 문자열을 입력받아서 10년 후 날짜를 출력하는 코드 작성

s = input('날짜(연/월/일) 입력해 주세요: ')
print(s)

s.split('/')

s_split = s.split('/')

print(s_split[0])

print('입력한 날짜의 10년 후: ', end="")

print(str(int(s_split[0])+10)+'년', end="")

print('입력한 날짜의 10년 후: ', end="")
print(str(int(s_split[0])+10)+'년', end="")
# end="" >>출력 끝에 아무 것도 출력 안됨
# >> 공백이나 개행문자 없이 다음 출력이 현재 출력 바로 뒤에 나타나게 함

"""map() : map(함수, 리스트)"""

pandemic = ['2020','02','01']
corona_period = list(map(int, pandemic))
corona_period

# 문자열 정렬

s ='닥터윌'
print(s)

# 가운데 정렬
s.center(10)

print(s.center(10, '*') )

# 왼쪽 정렬
s.ljust(10)

# 오른쪽 정렬
s.rjust(10)

s.zfill(10)

# 문자열 구성 파악하기

s = 'Multicampus'

s.isdigit() # 숫자냐?

s.isalpha() # 문자냐?

# isalnum() : 문자열의 모든 문자가 문자, 영어, 숫자인지 확인

s.isalnum()

"멀티캠퍼스".isalnum()

"멀티 캠퍼스".isalnum()

txt = "Hello123"
print(txt.isalnum())

txt = "Hello 123"
print(txt.isalnum())

# isspace()
'    '.isspace()

txt = 'Multi campus'
txt.isspace()

a = input('첫 번째 문자열 입력: ')
b = input('두 번째 문자열 입력: ')

result = a + " " +b
print(a, '+', b, '=', result )

