# -*- coding: utf-8 -*-
"""python_17_inter-mid_예외처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArtZCVmpOonu98IJCr40Rz24I4xBO6ZE

예외처리
"""

# Commented out IPython magic to ensure Python compatibility.
# %pwd
# present working directory (현재 작업폴더)

# /content/text.txt

# try ~ except

import os

try:
    os.remove('./python.txt')
except:
    print("그런 파일 없어요. 확인 좀 하세요.")

#  os.remove('/python.txt')
#  FileNotFoundError: [Errno 2] No such file or directory: '/python.txt'

# os.remove('./text.txt')

# '멀티' 글자를 모두 찾아서 출력하는 코드 작성

mycampus = "나는 현재 대한민국 최고의 IT 데이터분석 & 개발자 양성소인 멀티 캠퍼스 교육생이다.\
억대 연봉자, 데이터싸인어티스가 되겠다는 나의 꿈을 바로 이 곳, 멀티 캠퍼스에서 이룰 것이다."

posList = [ ]
position = 0

while True:
    try:
        multi = mycampus.index('멀티', position)
        posList.append(multi)
        position += 1
    except:
        break

print("멀티 글자 위치: ", sorted(list(set(posList))))

mycampus.index("멀티")

# 예외처리 (오류의 종류별 except 만들기)

num1 = input('숫자1: ')
num2 = input('숫자2: ')

try:
    num1 = int(num1)
    num2 = int(num2)

    while True:
        res = (num1/num2)

except ValueError:
    print("문자열을 입력하셨어요. 숫자로 입력 부탁드려용")
except ZeroDivisionError:
    print("0으로 나눌 수가 없어요. 다른 숫자 입력 부탁드려용")
except KeyboardInterrupt:
    print("강제종료 KEY 누르셨네요.")

