# -*- coding: utf-8 -*-
"""python_textbook_01_기초문법활용, 프로그램만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hIz3GmhbAAgD62IkfP4ieqrDN2PAAhm4
"""

# 파이썬 프로그램 준비하기

for i in range(1,11):
    print( str(i) +'번째 인사' )

# str() : 숫자 >> 문자로 변환

list(range(1,11))

# 기초문법으로 프로그램 만들기

for i in range(100):
    if i % 7 == 0: # 7의 배수
        print(i)

# 평균 나이 구하기

print((50+45+33+39+29+30) / 6)

a = (50+45+33+39+29+30) / 6
print(round(a, 2))

# round():반올림 함수
# '2'의 의미 : 소수점 2째 자리까지 표현

b = (50+45+33+39+29+30) // 6 # 몫
print(b)

# 반복문

num = [1,2,3,4,5,6,7,8,9]

for i in num:
    print(2 * i)

for i in range(2,10):
    print(i+2)

# for 문 두번 사용 >> 19단 곱셈표 출력하기

for i in range(2, 20):
    for j in range(1, 20):
        print(i*j)

"""19단 곱셈표"""

for i in range(2, 20):
    for each in range(2, 20):
        print(i, 'x', each, "=", i*each)
    print('-'*20)

"""부가가치세 출력 프로그램 만들기"""

# 부가가치세 = 물건값 * 1.1 (10% 가산)
# 예) 판매가 200만원 >> 181만 8천원 정도

5000 * (1+0.1)

# 부가세 미포함
5500 / 1.1

# 상황
# 오늘 먹은 점심 값 10,000원에 대한 부가세 얼마?

점심값 = 10000
실제가격 = 점심값 / 1.1
print(실제가격)

부가세 = 점심값 - 실제가격

print(부가세)
print(round(부가세, 2))

"""함수"""

# def(), lambda()

# def() : 특정한 함수 정의(definition)
# lambda(): 람다함수, 1회용 함수

y = lambda x : 3*x

print(y(12))

add = lambda a,b : a+b
print(add(2,3))

부가세포함가격 = lambda x :  1.1 * x

부가세포함가격(10000)

세전가격 = lambda x :  (x / 1.1)
print(round(세전가격(9000),2))

어린왕자 = '''여섯 살 적에 나는 '체험한 이야기'라는 제목의, 원시림에 관한 책에서 기막힌 그림 하나를 본 적이 있다.'''

# 슬라이싱
어린왕자[:10]

일부분_10개까지 = lambda x : x[:10]

일부분_10개까지(어린왕자)

"""환율 계산기"""

exchange  = lambda won : won * 0.0086
exchange(1000000)

# def() 함수사용(사용자 함수)

def add(a,b):
    return a+b

print(add(154,60))

# 나만의 계산시

def 내_계산기(a,b):
    return a+b, a-b, a*b, a/b

내_계산기(12,3)

print(type(내_계산기(12,3)))

# input() 함수로 사용자에게 입력 받기

입력 = input('숫자 하나 입력해 주세요: ')
print(입력)

type(입력)

# 문자 >> 숫자

입력값 = float(입력)
print(입력값)

# 홀수/짝수 구분기 만들기

def 홀짝구분():
    a = int(input('숫자 하나를 입력하세요. '))

    # 조건문 (홀짝 유무 확인)
    if a % 2 == 0:
        print("짝수")
    else:
        print("홀수")

홀짝구분()

"""서비스 가격 출력 프로그램 완성하기"""

# (단위: US$)
def service_price():
    # 서비스 종류
    service = input('서비스 종류를 입력하세요. 일반/스피드/특별: ')
    # 부가세 포함여부
    vat = input("부가세를 포함합니까? y/n: ") #value-added tax

    # 조건문
    if vat == 'y':
        if service == '일반':
            result = 25 * 1.1
        elif service == '스피드':
            result = 20 * 1.1
        elif service == '특별':
            result = 50 * 1.1
    if vat == 'n':
        if service == '일반':
            result = 25
        elif service == '스피드':
            result = 20
        elif service == '특별':
            result = 50

    print(round(result, 2), '입니다.')

service_price()

service_price()

