# -*- coding: utf-8 -*-
"""python_06_조건문과 반복문.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iIdOcUH5nw3MvTiTO79nTr_T9pb8xBH7

조건문
"""

'''
if (A):
    pass
if (B):
    pass
else:
'''

# 주민등록번호로 성별(남/여) 구분하기

number = int(input())

if number % 2 == 0:  # 짝수 : number 2로 나눈 뒤 나머지가 0이니깐
    print("여자입니다")
else:
    print("남자입니다.")

# 의류 사이즈 분류
# 100에서 10단위로 커지는 사이즈에서
# 분류기준
# 1) size가 150이하 : 아동용
# 2) size가 190이상 : 맞춤옷
# 3) 그외: 성인용

size = int(input())

if size <= 150:
    print('아동용')
elif size >= 190:
    print('맞춤옷')
else:
    print('성인용')

"""반복문"""

# for 반복문

'''
for 하나 in 컬렉션:
    수행할 동작

'''

for i in range(3):
    for j in range(2):
        print(i, j)

list(range(3))

list(range(2))

"""while
- 무한 반복 (반복 지옥)
- 반드시 정지조건(pass, continue, break)
"""

'''
1. break : while 반복문 밖으로 빠져나감
2. continue: 다음 소스 코드를 실행하지 않고 다음 단계로 넘어감
3. pass: 아무 것도 하지 않고 넘김
'''

number = 0  # 초기화

while True:
    if number > 4:  # 정지조건
        break

    print(number)
    number = number + 1

# sum = 0
# mul = 1

while True:
    if number > 4:
        break

        print(number)
    number = number + 1

# continue

number = 0

while number < 6:
    number = number + 1
    if number > 4:
        continue
    print(number)

# pass

number = 0

while number < 6:
    if number % 2 == 0:  # 짝수
        pass
    else:
        print('홀수')

    number = number +1

