# -*- coding: utf-8 -*-
"""python_07_method.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G7xUfEfzh9nJiHWZD4agndBn6t6v3a43

append() : list에서 추가
"""

list_ = []
list_.append(1)
list_.append(2)
list_.append(3)

print(list_)

# .sort() 정렬
list_2 = ['banana', 'apple', 'caramel']

list_2.sort() # 오름차순 정렬(default)

print(list_2)

list_3 = [5,4,3,2,1]
list_3.sort()

print(list_3)

"""sequence 의 indexing 과 slicing
- indexing: sequence 에서 한 원소를 가져오는 것
- slicing: sequence 에서 일부분을 가져오는 것
"""

list_4 = [1,2,3,4,5,6]

print(list_4[3:])

print(list_4[:2])
print(list_4[:])
print(list_4[::-1])

my_str = "impossible"
my_list = ['Apple', 'Banana', 'Chamwae', 'Durian']

my_str[2] # indexing

my_list[2:] # slicing

"""sequence 길이와 멤버 조사하기"""

my_str = 'abc'
print(len(my_str)) # len() : length (sequence의 크기/길이)
print('d' in my_str) # False >> 존재하지 않음

"""Dictionary 추가 연습"""

my_dict = {"사과":"apple", "바나나":"banana", "당근":"carrot"}

my_dict["당근"]

del my_dict["바나나"]

print(my_dict)

# 원소 추가하려면?
my_dict["망고"] = 'mango'

print(my_dict)

# 이것도 가능할까?

bad_dict = {1:"one", 1:"yi"}

print(bad_dict)

good_dict = {1:['one','yi'], 2:['two','er']}

print(good_dict)
print(good_dict[2])

print(good_dict[2][1])

print(good_dict[2][0])

#{[1,2,3]: "num"}
#TypeError: unhashable type: 'list'
# 리스트는 key 로 사용하지 못함

{(1,2,3): "num"}

# tuple(상수) : immutable(변경 불가)>> 고정된 값 >> dict 가능

my_dict = {}

my_dict[1] = 'integer'
my_dict['a'] = 'string'
my_dict[(1,2,3)] ='tuple'

print(my_dict)

# try ~ except : 에러 방지용

my_dict = {}

my_dict[1] = 'integer'
my_dict['a'] = 'string'
my_dict[(1,2,3)] ='tuple'

try:
    my_dict[[1,2,3]] = 'list'

except TypeError:
    print("unhashable type: 'list' >> list는 딕셔너리의 key가 될 수 없어요")





